site_name: My Docs
theme: 
  name: material
  custom_dir: overrides
plugins:
  - blog:
      blog_dir: blog
      post_dir: "{blog}/posts"
      authors_file: "{blog}/.authors.yml"
      authors_profiles: true
      authors_profiles_name: Authors
  - rss:
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags

nav:
  - index.md
  - Blog:
    - blog/index.md

